// src/lib/components/LibrarySearch.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import Fuse from 'fuse.js';
  import { Input } from '$lib/components/ui/input';

  export let libraries: Array<{
    id: string;
    groupId?: string;
  }>;
  export let onSelect: (library: any) => void;

  let search = '';
  let fuse: Fuse<any>;
  let results = libraries;

  onMount(() => {
    fuse = new Fuse(libraries, {
      keys: ['id', 'groupId'],
      threshold: 0.3,
      includeScore: true
    });
  });

  $: {
    if (search.trim() && fuse) {
      const searchResults = fuse.search(search);
      results = searchResults.map(result => result.item);
    } else {
      results = libraries;
    }
  }
</script>

<div class="w-full space-y-2">
    <Input
            type="search"
            placeholder="Search libraries..."
            bind:value={search}
            class="w-full"
    />

    <div class="h-[60vh] overflow-y-auto">
        <div class="space-y-1">
            {#each results as library}
                <button
                        on:click={() => onSelect(library)}
                        class="w-full p-2 text-left hover:bg-accent rounded-md transition-colors"
                >
                    <div class="font-medium">{library.id}</div>
                    {#if library.groupId}
                        <div class="text-sm text-muted-foreground">
                            {library.groupId}
                        </div>
                    {/if}
                </button>
            {/each}
        </div>
    </div>
</div>

// packages/spa/src/components/LibrarySearch.tsx
'use client';

import {ChangeEvent, useEffect, useState} from 'react';
import Fuse from 'fuse.js';
import {Input} from '@/components/ui/input';
import {Library} from '@/lib/types.ts';

interface LibrarySearchProps {
  libraries: Library[];
  onSelect: (library: Library | null) => void;
  selectedLibrary: Library | null;
}

export default function LibrarySearch({
                                        libraries,
                                        onSelect,
                                        selectedLibrary,
                                      }: LibrarySearchProps) {
  const [search, setSearch] = useState('');
  const [fuse, setFuse] = useState<Fuse<Library>>();
  const [results, setResults] = useState(libraries);

  useEffect(() => {
    setFuse(new Fuse(libraries, {
      keys: ['id', 'groupId'],
      threshold: 0.3,
      includeScore: true,
    }));
  }, [libraries]);

  useEffect(() => {
    if (search.trim() && fuse) {
      const searchResults = fuse.search(search);
      setResults(searchResults.map(result => result.item));
    } else {
      setResults(libraries);
    }
  }, [search, fuse, libraries]);

  const handleSearchChange = (e: ChangeEvent<HTMLInputElement>) => {
    setSearch(e.target.value);
  };

  return (
    <div className="w-full h-full flex flex-col">
      <Input
        type="search"
        placeholder="Search libraries..."
        value={search}
        onChange={handleSearchChange}
        className="w-full mb-2 flex-shrink-0"
      />

      <div className="flex-1 overflow-y-auto min-h-0 pr-2 custom-scrollbar">
        <div className="space-y-1">
          {results.map((library) => (
            <button
              key={library.id}
              onClick={() => onSelect(library)}
              className={`w-full p-2 text-left hover:bg-accent rounded-md transition-colors
                ${selectedLibrary?.id === library.id ? 'bg-primary text-primary-foreground' : ''}`}
            >
              <div className="font-medium">{library.id}</div>
              {library.groupId && (
                <div className="text-sm text-muted-foreground">
                  {library.groupId}
                </div>
              )}
            </button>
          ))}
        </div>
      </div>
    </div>
  );
}
